<?xml version="1.0" encoding="UTF-8"?><testrun name="BoardTest" project="20-unitetesting-app" tests="3" started="3" failures="1" errors="0" ignored="0">
  <testsuite name="co.techlabs.tictaktoe.BoardTest" time="0.064" displayname="BoardTest" uniqueid="[engine:junit-jupiter]/[class:co.techlabs.tictaktoe.BoardTest]">
    <testcase name="testIsBoardFull" classname="co.techlabs.tictaktoe.BoardTest" time="0.039" displayname="testIsBoardFull()" uniqueid="[engine:junit-jupiter]/[class:co.techlabs.tictaktoe.BoardTest]/[method:testIsBoardFull()]"/>
    <testcase name="testIsBoardNotFull" classname="co.techlabs.tictaktoe.BoardTest" time="0.003" displayname="testIsBoardNotFull()" uniqueid="[engine:junit-jupiter]/[class:co.techlabs.tictaktoe.BoardTest]/[method:testIsBoardNotFull()]"/>
    <testcase name="testSetCellMark" classname="co.techlabs.tictaktoe.BoardTest" time="0.022" displayname="testSetCellMark()" uniqueid="[engine:junit-jupiter]/[class:co.techlabs.tictaktoe.BoardTest]/[method:testSetCellMark()]">
      <failure>
        <expected>X</expected>
        <actual>co.techlabs.tictaktoe.Cell@b3d7190</actual>org.opentest4j.AssertionFailedError: expected: &lt;X&gt; but was: &lt;co.techlabs.tictaktoe.Cell@b3d7190&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)&#13;
	at co.techlabs.tictaktoe.BoardTest.testSetCellMark(BoardTest.java:49)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at java.util.ArrayList.forEach(Unknown Source)&#13;
	at java.util.ArrayList.forEach(Unknown Source)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
